config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates     :title, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @pagy, @articles = pagy(Article.all)
  end

  def show; end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to article_url(@article), notice: :create
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_to article_url(@article), notice: :update
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: :destroy
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <div class='box'>
    <h2 class='title is-5'>Title:</h2>
    <p>
      <%= article.title %>
    </p>
    <h2 class='title is-5'>Body:</h2>
    <p>
      <%= article.body.html_safe %>
    </p>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with model: article   do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, 'error') %> prohibited this article from being saved:</h2>
      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: 'display: block', class: 'label' %>
    <%= form.text_field :title, class: 'input' %>
  </div>
  <div class='field'>
    <%= form.label :body, style: 'display: block', class: 'label' %>
    <%= form.text_area :body, class: 'tinymce', rows: 20, cols: 80, id: 'TinyEditor' %>
    <%= tinymce %>
  </div>
  <div>
    <%= form.submit class: 'button is-primary is-light' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 class='title has-text-centered'>Editing article</h1>
<div>
  <%= link_to article_path(@article), data: { turbo: false }, class: 'is-size-4 has-text-primary' do %>
    Show
  <% end %>
  <i class="fa-solid fa-ellipsis-vertical"></i>
  <i class="fa-solid fa-ellipsis-vertical"></i>
  <i class="fa-solid fa-ellipsis-vertical"> </i>
  <%= link_to articles_path, class: 'is-size-4 has-text-primary' do %>
    Back to Articles
  <% end %>
  <%= render 'form', article: @article %>
  <br>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>
<div class='container-flex'>
  <h1 class='title has-text-centered has-text-primary-dark'>Articles</h1>
  <div id="articles">
    <% if @pagy.pages > 1 %>
      <div class="level-right py-2">
        <nav class='pagination is-rounded is-small'>
          <%== pagy_bulma_nav(@pagy, size: [1, 2, 2, 1], pagy_id: 'pagy_nav') %>
        </nav>
      </div>
    <% end %>
    <% @articles.each do |article| %>
      <%= render article %>
      <p class="control has-icons-left">
        <%= link_to article, class: 'is-size-4 has-text-primary' do %>
          <i class="fas fa-search" aria-hidden="true"></i>
          Show article
        <% end %>
      </p>
    <% end %>
  </div>
  <%= link_to 'New article without turbo', new_article_path, data: { turbo: false }, class: 'button is-success is-outlined' %>
  <%= link_to 'New article with turbo', new_article_path, class: 'button is-danger is-outlined' %>
</div>

app/views/articles/new.html.erb
<div>
  <%= link_to articles_path, class: 'is-size-4 has-text-primary' do %>
    <i class="fa-regular fa-circle-left"></i>
    Back to articles
  <% end %>
</div>
<div class='box'>
  <h1 class='title'>New Article in TinyMCE editor</h1>
  <%= render 'form', article: @article %>
  <br>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>
<h1 class='title has-text-centered'>Show article</h1>
<%= render @article %>
<div>
  <%= link_to edit_article_path(@article), data: { turbo: false }, class: 'is-size-4 has-text-primary' do %>
    Edit article
  <% end %>
  <i class="fa-solid fa-ellipsis-vertical"></i>
  <i class="fa-solid fa-ellipsis-vertical"></i>
  <i class="fa-solid fa-ellipsis-vertical"></i>
  <%= link_to articles_path, class: 'is-size-4 has-text-primary' do %>
    Back to Articles
  <% end %>
  <%= button_to 'Destroy this article', @article, method: :delete, class: 'button is-danger is-outlined' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= tinymce_assets %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class='container is-full-widthi gap-2'>
      <%= yield %>
    </div>
  </body>
</html>